### ISSUE TITLE
Listing command line handlers produces no output

### ISSUE THREAD

**Issue by hernanmd** [pharo-project/pharo-zeroconf#15]
On Windows 8.1 with MSYS the following command:

```bash
$ ./pharo Pharo.image --list
```
produces no output.

Image (currently 6.1) downloaded as:

```bash
wget -O- --no-check-certificate https://get.pharo.org/ | bash
```

Version information:

```bash
$ bash --version
GNU bash, version 3.1.23(1)-release (i686-pc-msys)
Copyright (C) 2005 Free Software Foundation, Inc.
```

**Comment by cdlm** [comment]
Unless I missed something, command line handlers are unrelated to zeroconf; report this at http://bugs.pharo.org instead.

FYI https://github.com/cdlm/clap-st should eventually take over command line handling.
